config/routes.rb
Whatfailed::Application.routes.draw do
  
  root :to => "posts#index"
  
  # omniauth
    match "/signin" => "sessions#new", :as => :signin
    match "/auth/:provider/callback" => "sessions#create"
    match "/signout" => "sessions#destroy", :as => :signout
    match "/auth/failure", to: "sessions#failure"
    resources :identities
  
  # posts
    resources :votes
    resources :posts do
      post :vote_for, :on => :member
      post :vote_against, :on => :member
    end
  
  #login
    # match "/login" => "posts#login", :as => :login

  # tags
    get '/tags' => "tags#index"
    get '/tags/:id' => "tags#show", :as => :tag
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :url, :content, :tag_tokens, :tags, :created_at
  has_friendly_id :title, :use_slug => true
  has_many :tagships
  has_many :tags, :through => :tagships
  attr_reader :tag_tokens
  belongs_to :user
  cattr_reader :per_page
  @@per_page = 10
  
  validates :title, :presence => true
  validates :url, :allow_blank => true,
                  :format => { :with => /^(http|https)/, :message => "needs to start with http:// or https://"}
 
  acts_as_voteable
  
 def tag_tokens=(ids)
   self.tag_ids = ids.split(",")
 end

 def belongs_to?(user)
   self.user_id == user.id
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authed, :except => [:index, :show]
  
  def index
    @posts = Post.all
    @posts = Post.paginate :page => params[:page], :order => 'created_at DESC'
    
    respond_to do |format|
      format.html #index.html.erb
      format.xml  { render :xml => @posts }
      format.atom
    end
  end

  def show
    @post = Post.find(params[:id])
    @votes = @post.votes

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.create(params[:post])
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
  
  def vote_for
    begin
      if current_user.nil?
         flash[:error] = "Please login first!"
      else
        if current_user.voted_for?(@post = Post.find(params[:id]))
          flash[:notice] = "You already voted up"
        else
          @vote_for = current_user.vote_exclusively_for(@post = Post.find(params[:id]))
          @vote_for.save!
        end
        redirect_to :back
       end
      rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def vote_against
    begin
      if current_user.nil?
         flash[:error] = "Please login first!"
      else
        if current_user.voted_against?(@post = Post.find(params[:id]))
          flash[:notice] = "You already voted down"
        else
          @vote_for = current_user.vote_exclusively_against(@post = Post.find(params[:id]))
          @vote_for.save!
        end
        redirect_to :back
       end
      rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def login
    # respond_to do |format|
    #   format.html #login.html.erb
    # end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  
# todo: Check for http, if not include it  

  def header(post)
    if post.url.blank?
      link_to post.title, post
    else
      link_to post.title, post.url, html_options = { :target => "_blank" }
    end
	end
	
	def link(post)
	    if post.url?
	      link_to "(#{URI.parse(post.url).host})", post.url, html_options = { :target => "_blank" }
	    end
	end
end

app/views/posts/_comment.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'whatfailedus'; // required: replace example with your forum shortname

    // The following are highly recommended additional parameters. Remove the slashes in front to use.
    var disqus_developer = 1; // developer mode is on, 0 is off
	  var disqus_identifier = '<% @post.cached_slug %>';
    // var disqus_url = '<% @post.cached_slug %>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/posts/_form.html.erb
<div id="submit" class="prefix_1 grid_5">
<%= form_for @post do |f| %>
  <div><label>#Title</label></div>
  <p><%= f.text_field :title, :value => params[:title] %></p>
  <div><label>#URL</label></div>
  <p><%= f.text_field :url, :value => params[:url] %></p>
	<div><label>#FailTags</label></div>
	<p><%= f.text_field :tag_tokens, "data-pre" => @post.tags.map(&:attributes).to_json %></p>
	<div><label>#WhatFailed?</label></div>
	<p><%= f.text_area :content %></p>
	<p><%= f.submit %></p>
<% end %>

</div><!--.submit-->

app/views/posts/_share.html.erb
<div class="grid_1" id="tag-on-post">
  <%= link_to(image_tag('Thumbs-up-icon.png', :alt => 'Vote up', :border => 0), vote_for_post_path(@post), :method => :post ) %>
  <span style="vertical-align:super;"><%= "#{@post.plusminus}" %></span>
  <%= link_to(image_tag('Thumbs-down-icon.png', :alt => 'Vote down', :border => 0), vote_against_post_path(@post), :method => :post) %>
</div>
<div class="grid_1" ><%= tweet_button(:url => post_url(@post), :text => "'#{@post.title}' #{@post.tags.map(&:name).map { |t| '#'+t }.join(' ')}", :count => "horizontal" )%></div>
<div class="grid_1 fb-like" data-href="<% "#{post_url(@post)}" %>" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false" style="margin:0px 45px;"></div>

app/views/posts/_submit.erb
<div id="submit">
<%= form_for @post do |f| %>
  <div><label>Title</label></div>
  <p><%= f.text_field :title %></p>
  <div><label>URL</label></div>
  <p><%= f.text_field :url, label: "URL" %></p>
	<p><%= f.text_area :content, label: "Content" %></p>
	<p><%= f.label :tag_tokens, label: "#FailTags" %></p>
	<p><%= f.text_field :tag_tokens, "data-pre" => @post.tags.map(&:attributes).to_json %></p>
	<p><%= f.submit %></p>
<% end %>
</div><!--.submit-->

app/views/posts/_tag.html.erb
<!-- <b>Tags:</b>
<%= @post.tags.each do |tag| %>
<%= tag.name.to_json %>
<% end %> -->

<!-- <%= form_for(@post) do |f| %> -->
<div class="field">
<b><%= f.label :tag_tokens, "Tags:" %><b/>
<%= f.text_field :tag_tokens, "data-pre" => @post.tags.map(&:attributes).to_json %>
<%= f.submit 'Update' %>
<% end %>
<div/>

app/views/posts/edit.html.erb
<% title 'Editing Post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% title "Startup Failures" %>

<%= render :partial => "layouts/post" %>

app/views/posts/login.html.erb
 <span class="nav-button"><%= link_to "Login with Twitter", "/auth/twitter" %></span>
<span class="nav-button"><%= link_to "Login with Facebook", "/auth/facebook" %></span>

app/views/posts/new.html.erb
<% title 'Submit #Fail' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<script type="text/javascript">
if( window.opener ) {
    window.close();
}
</script>

<% content_for :ogmetaurl do %>
  <%= h(post_url(@post)) %>
<% end %>

<% title "#{@post.title}" %>
<div/ class="prefix_1 grid_8">
<p>
	Posted by <%= @post.user.name %> <%= time_ago_in_words(@post.created_at) %> ago

<% if current_user %>
	<% if @post.belongs_to?(current_user) %>
		( <%= link_to "edit", edit_post_path(@post) %> ,
		<%= link_to "delete", @post, :confirm => 'Are you sure?', :method => :delete %> )
	<% end %>
<% end %>

</p>

<p>
  <% if @post.url.blank? == false %>
    <%= link(@post) %>
  <% end %>
</p>

<% if @post.content.blank? == false %>
  <%= raw RDiscount.new(@post.content).to_html %>
<% end %>

<%= form_for(@post) do |f| %>
<table id="tags-editor">
<tr>
	<% if current_user %>
		<td><%= f.text_field :tag_tokens, "data-pre" => @post.tags.map(&:attributes).to_json %></td>
		<td><%= f.submit 'Update' %></td>
	<% else %>
		<td><%= f.text_field :tag_tokens, "data-pre" => @post.tags.map(&:attributes).to_json, :disabled => true %></td>
		<td><%= f.submit 'Please Login to Update', :disabled => true %></td>
	<% end %>
</tr>
</table>
<% end %>

<div>
  <%= render 'share' %>
</div>

<br class="clear" />

<%= render 'comment' %>
</div><!--.-->