config/routes.rb
Whatfailed::Application.routes.draw do
  
  root :to => "posts#index"
  
  # omniauth
    match "/signin" => "sessions#new", :as => :signin
    match "/auth/:provider/callback" => "sessions#create"
    match "/signout" => "sessions#destroy", :as => :signout
    match "/auth/failure", to: "sessions#failure"
    resources :identities
  
  # posts
    resources :votes
    resources :posts do
      post :vote_for, :on => :member
      post :vote_against, :on => :member
    end
  
  #login
    # match "/login" => "posts#login", :as => :login

  # tags
    get '/tags' => "tags#index"
    get '/tags/:id' => "tags#show", :as => :tag
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title)
    content_for(:title) { h(page_title.to_s) }
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_post.html.erb
<% @posts.each do |post| %>  

<div id="post" class="grid_7 push_1" >
  <span id="title"><%= header(post) %></span>
  <span id="url"<%= link_to link(post) %></span>
  <div id="tags">
    <% post.tags.each do |tag| %>
      <span id="tag"><%= link_to "##{tag.name}", tag %></span>
    <% end %>
  </div><!--.tags-->
  <div id="info">
    Posted by <%= post.user.name %> <%= time_ago_in_words(post.created_at) %> ago
    [ <%= link_to '{num} Comment', post_path(post, :anchor => "disqus_thread") %> ]
  </div><!--.info-->
</div><!--.post-->

<div id="social" class="grid_1 push_1" >
  <div style="margin-bottom: 5px;"><%= tweet_button(:url => post_url(post), :text => "'#{post.title}' #{post.tags.map(&:name).map { |t| '#'+t }.join(' ')}", :count => "horizontal" )%></div>
  <div class="fb-like" data-href="<%= post_url(post) %>" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
</div><!--.social-->
<div id="tag-post" class="grid_1 pull_7" >
  <%= link_to(image_tag('Thumbs-up-icon.png', :alt => 'Vote up', :border => 0), vote_for_post_path(post), :method => :post ) %><br/>
  <div style="margin:auto; width:50%;"><%= "#{post.plusminus}" %></div>
  <%= link_to(image_tag('Thumbs-down-icon.png', :alt => 'Vote down', :border => 0), vote_against_post_path(post), :method => :post) %>
</div><!--.tag-post-->
<% end %>

<br style="clear:both;"/>
<div id="paginate" class="push_1">
<p><%= will_paginate @posts %></p>
<p><%= page_entries_info @posts %></p>
</div><!--.paginate-->

app/views/layouts/application.html.erb
<html>
 <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# whatfailed: http://ogp.me/ns/fb/whatfailed#">
 <meta property="fb:app_id"      content="297086536985505">
 <meta property="og:type"        content="<%= content_for?(:ogmetaurl) ? "whatfailed:article" : "website" %>">
 <meta property="og:url"         content="<%= content_for?(:ogmetaurl) ? "#{yield(:ogmetaurl)}".strip : "http://www.whatfailed.us/" %>">
 <meta property="og:title"       content="<%= content_for?(:title) ? yield(:title) : "WhatFailed.us" %>">
 <meta property="og:site_name"   content="WhatFailed.us">
 <meta property="og:description" content="startup insights">
 <meta property="og:image"       content="http://www.whatfailed.us/images/emu_twitter_logo.jpg">
 <link rel="canonical" href="http://www.whatfailed.us/" />
 <meta name="google-site-verification" content="4ccQVJEbRYim3rk-9HMTLJBhy2n3rg2jGg2i4VaJUV4" />
 <title><%= content_for?(:title) ? yield(:title) : "WhatFailed.us" %></title>
  <%= stylesheet_link_tag "960", "app", "token-input-facebook", "jquery.qtip" %>
  <%= javascript_include_tag :defaults, "jquery.tokeninput", "jquery.qtip", "jquery.qtip.min" %>
  <%= csrf_meta_tag %>
  <%= yield(:head) %>
  <%= auto_discovery_link_tag :atom, posts_path(:atom) %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-27696456-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>

<body>
	
<div id="container" class="container_12">
<div id="header" class="grid_12" >
  <div id="logo" class="grid_3 alpha" >
    <%= link_to image_tag("WhatFailed_1_small.png", :alt => "Home", :border => 0), :root %>
  </div><!--.logo-->
	 <div id="nav" class="grid_2" >
	   <span class="nav-button"><%= link_to 'Home', :root %></span>
	   <span class="nav-button" title="add a startup failure"><%= link_to 'Submit New', new_post_path %></span>
   </div><!--.nav-->
   <div id="nav-user" class="grid_6 omega" >
     <span class="nav-button" title="drag this to your bookmark bar"><%= link_to 'WF Bkmrklt', 'javascript:var win = window.open( "http://www.whatfailed.us/posts/new?popup=true&title=" + encodeURIComponent(document.title) + "&url=" + encodeURIComponent(document.location), "", "width=500,height=500,scrollbars=1" );'%></span>
     <span class="nav-button"><a href="http://whatfailed.wufoo.com/forms/m7x3s5/" onclick="window.open(this.href,  null, 'height=713, width=680, toolbar=0, location=0, status=1, scrollbars=1, resizable=1'); return false" title="tell us what you think">Feedback</a></span>
		<% if current_user %>
		  Signed in as <%= current_user.name %>
		  <span class="nav-button"><%= link_to "Sign Out", signout_path %></span>
		<% else %>
		  <span class="nav-button"><%= link_to "Sign In", signin_path %></span>
		<% end %>
  </div><!--.nav-user-->
</div><!--.header-->

<div id="content" class="grid_10" >
  <br/>
<div id="title" class="grid_7 push_1 alpha">
    <% if yield(:title).present? %>
      <h1><%= yield(:title) %></h1>
    <% end%>
</div><!--title-->
  
<div id="message" class="grid_2 push_1">
  <%- flash.each do |type, msg| -%>
  <div class="msg" id="<%= type %>"><%= msg %></div>
  <%- end -%>
</div><!--.message-->
    <%= yield %>
    <br style="clear:both;"/>
    <div id="paginate" class="push_1" style="text-decoration:none">
      <p><%= link_to 'Back', :back %></p>
    </div><!--.pagination-->  
</div><!-- .content -->
  <div id="sidebar" class="grid_2 omega" >
    <div style="margin-bottom:20px" ><%= link_to image_tag("feed-icon.png", :alt => "Atom Feed", :border => 0), posts_path(:atom) %></div>
    <h3>#FailTags</h3>
    <div style="margin-bottom:30px">
      <% Tag.includes(:posts).order('posts_count DESC').each do |tag| %>
      <div id="tag-index" style="padding:6px;">
      <%= link_to "##{tag.name} (#{tag.posts.length})", tag %>
    </div>
    <% end %>
    <div id="community">
      <div class="fb-like-box" data-href="http://www.facebook.com/apps/application.php?id=297086536985505" data-width="292" data-show-faces="false" data-stream="false" data-header="true"></div><br/>
      <div style="margin-left:10px"><a href="https://twitter.com/whatfailed" class="twitter-follow-button" data-show-count="false">Follow @whatfailed</a></div>
    </div><!--.community-->
  </div><!-- .sidebar -->
</div><!-- .container -->


<div id="fb-root"></div>
<script type="text/javascript">var _kiq = _kiq || [];</script>
<script type="text/javascript" src="//s3.amazonaws.com/ki.js/25079/4Yk.js" async="true"></script>
<script src="//platform.twitter.com/widgets.js" type="text/javascript"></script>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'whatfailedus'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());


    window.fbAsyncInit = function() {
      FB.init({
          appId: '297086536985505', // Your Facebook ID
          status: true, 
          cookie: true,
          xfbml: true
      });
    };
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=297086536985505";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<script type="text/javascript">
$(document).ready(function()
{
    // Match all A links with a title tag and use it as the content (default).
  $('a[title]').qtip();
  $('span[title]').qtip();
  $("span#title").each(function(){
     $(this).qtip({
        content: $(this).html()
     });
  });
});
</script>
<br class="clear" />
</body>
</html>